version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=iet-overflow
      - POSTGRES_USER=sg0311725
      - POSTGRES_PASSWORD=mario
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db